### PR TITLE
Test 23.2 during staging

### PR DESCRIPTION
**Pull request by aradi**
Note: URL points to a personal stage branch currently

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] ~Bumped the build number (if the version is unchanged)~
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Review by bhourahine — APPROVED** [review]
Fine to merge, but the macOS behaviour is strange.

**Comment by aradi** [comment]
It seems to be a race condition. I am not sure, what happens there, probably there is something strange about how `OBJECT` libraries are transfered by CMake into ninja rules...

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
@conda-forge-admin please rerender

**Comment by aradi** [comment]
@conda-forge-admin please rerender

**Comment by aradi** [comment]
@conda-forge-admin please rerender

**Comment by aradi** [comment]
@conda-forge-admin rerender

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
