### PR TITLE
Rebuild for new ELSI/ELPA version

### PR DESCRIPTION
**Pull request by awvwgk**
MNT: Re-rendered with conda-build 3.21.7, conda-smithy 3.16.1, and conda-forge-pinning 2022.01.11.08.53.25

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Requires https://github.com/conda-forge/elpa-feedstock/pull/13
Requires [rebuild of ELSI](https://github.com/conda-forge/elsi-feedstock/pull/14)

### CODE REVIEW

**Review by bhourahine — APPROVED** [review]
LGTM (unfortunate about check fails though)

**Comment by aradi** [comment]
Stupid question: Do we need the build, just because the ELPA compatibility is set up very strictly in the recipe? If yes, we should probably reconsider our very strict policy, so that newer (but backwards compatible) external libraries would not enforce a rebuild of DFTB+.

**Comment by aradi** [comment]
Note: the CI fails due to `Imported target "elsi::elsi" includes non-existent path`. So probably something is broken with the ELSI package?

**Comment by awvwgk** [comment]
ELSI is not yet rebuild, will trigger this soon but still waiting for CDN sync.

**Pull request merged**
