### PR TITLE
Update to Release 20.2.1

### PR DESCRIPTION
**Pull request by aradi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Review by bhourahine — COMMENTED** [review]
The rerender didn't add a minimum python version as a [requirement block](https://github.com/conda-forge/conda-forge.github.io/issues/566), presumably as it has no idea what to use.
@awvwgk can this just go into the meta.yaml ?
@aradi python 3.5 or something else for minimum?
Also, the out of date feedstock checks look a little worrying (probably just need to sort out workflow for when there are active PRs around).

**Comment by aradi** [comment]
In case it can be specified somewhere, it should be Python 3.6.

In the mean time I've realized, that another PR (#9) was automatically triggered by the robot wth the same purpose...

**Comment by awvwgk** [comment]
This recipe doesn't require Python, therefore there is no need to specify any Python version here.

**Review by awvwgk — APPROVED** [review]

**Pull request merged**
