### PR TITLE
Upgrade to version 21.2

### PR DESCRIPTION
**Pull request by aradi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by awvwgk** [comment]
@conda-forge-admin, please rerender

**Review by awvwgk — COMMENTED** [review]
Can we do one step at a time? Let's get the new version to build first before we add features on top.

Some notes:
- I didn't get DFTB+ to build against ARPACK when first building for conda-forge
- to use PkgConf in Cmake you have to add `pkg-config` to the build requirements
- using ELSI or Plumed adds a C++ dependency in DFTB+'s CMake files, therefore we need a C++ compiler in build
- I triggered a rebuild of libnegf, this will take ~2h at least before being available here

**Comment by aradi** [comment]
OK, then I'll reset things, so that we only have an updated URL for the new version and we can extend the components once that builds.

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
By the way, as for arpack, I've managed to build DFTB+ with it locally (with all the extensions I've added to the recipe :wink), it was only the MPI-version which failed.

**Comment by aradi** [comment]
OK, just to make my statement from above more precise: I've managed to create a build *locally* with arpack for linux/linux_64, so if you had problems with arpack on other platforms, it may still persist.

**Comment by awvwgk** [comment]
Good, only one build of libnegf is open, will be available in an hour or so. Now we can look into adding new features.

Also, might be worth to switch to cross-compilation for ppc64le and aarch64.

**Comment by aradi** [comment]
As far as I can judge, it works as it should. I've force pushed the same commit again to re-trigger the CI, as the aarch64-nompi was hanging for about 4 hours...) Only ChIMES is not included yet, as conda-forge/staged-recipes#17168 had been not merged yet. I'd suggest to wait until tomorrow morning, and if not included at that point yet, we should merge this PR witihout the ChIMES support, since I want to send out the official release announcement tomorrow morning.

@awvwgk please, have a look at it, whether you can see any problems. Thanks, and I also really appreciate all the efforts you've put into packaging our numerous dependencies. Thanks to that, the Conda package is almost feature complete (apart of xTB, of course, which we are still waiting eagerly for :wink: )

**Comment by aradi** [comment]
OK, it seems, ChIMES had just been merged :fireworks: So, probably there is still a chance to add ChiMES till tomorrow morning!

**Comment by awvwgk** [comment]
Let's switch to cross-compilation rather than emulation for the Linux/aarch64 builds. Also, tblite is staged here: https://github.com/conda-forge/staged-recipes/pull/17227, and could be available soon. But let's not wait for tblite and just rebuild once it is merged.

**Review by awvwgk — APPROVED** [review]

**Pull request merged**
