### PR TITLE
Release 21.1

### PR DESCRIPTION
**Pull request by aradi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by awvwgk** [comment]
`libmbd` has not been migrated to ppc64le and aarch64 yet.

**Comment by aradi** [comment]
@awvwgk Thanks a lot, I was not aware of that. I've tried to set up now an architecture dependent option, let"s see, whether it works out. :wink:

**Comment by awvwgk** [comment]
I think it is easier to just add support in libmbd for those architectures, see https://github.com/conda-forge/libmbd-feedstock/issues/17.

**Comment by awvwgk** [comment]
Successfully added ppc64le and aarch64 support to libmbd. It will take ~2h after the package upload to propagate through the CDN before being available here, nothing we can do here for today.

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Review by awvwgk — APPROVED** [review]

**Review by bhourahine — APPROVED** [review]

**Pull request merged**
